config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users, except: [:new, :create] do
    member do
      get :following, :followers
    end
  end
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	has_many :microposts, dependent: :destroy
	has_many :active_relationships, class_name:  "Relationship",
																	foreign_key: "follower_id",
																	dependent: 	 :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :passive_relationships, class_name: "Relationship",
																	 foreign_key: "followed_id",
																	 dependent: :destroy
	has_many :followers, through: :passive_relationships, source: :follower

	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest
	validates :name, presence: true, length: { minimum: 3, maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		digest ? BCrypt::Password.new(digest).is_password?(token) : false
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def activate
		update_columns(activated: true, activated_at: Time.zone.now)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	def create_reset_digest
  	self.reset_token = User.new_token
  	update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
  	UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	def feed
		#user_ids = following_ids.push(self.id)
		#Micropost.where("user_id IN (?)", user_ids).order(created_at: :desc)
		following_ids = "SELECT followed_id FROM relationships
										 WHERE follower_id = :user_id"
		Micropost.where("user_id IN (#{following_ids})
										 OR user_id = :user_id", user_id: id).order(created_at: :desc)
	end

	def follow(other_user)
		active_relationships.create(followed_id: other_user.id)
	end

	def unfollow(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end

	def following?(other_user)
		following.include?(other_user)
	end

	private

		def downcase_email
			self.email.downcase!
		end

		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.where(activated: true).paginate(page: params[:page], per_page: 15)
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
      flash[:success] = "Please check your email to activate your account!"
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 7)
    unless @user.activated?
      flash[:danger] = "User is not yet verified!"
      redirect_back_or root_url
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile details updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user?(@user)
      @user.destroy
      flash[:success] = "Your profile has been successfully deleted!"
      redirect_to root_path
    else
      @user.destroy
      flash[:success] = "Profile successfully deleted!"
      redirect_to users_path
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 7)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 7)
    render 'show_follow'
  end

  private

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:danger] = "You are not authorized for this action!"
        redirect_to root_url
      end
    end

    def admin_user
      unless current_user.admin? || current_user?(User.find(params[:id]))
        flash[:danger] = "You can only delete your own profile!"
        redirect_to current_user
      end
    end

	  def user_params
	  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, size: 50)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
	<%= hidden_field_tag :followed_id, @user.id %>
	<%= f.submit "Follow", class: "btn btn-info" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @user == current_user %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_form.html.erb
<div class="content-card">
	<h1 class="center"><%= yield(:form_title) %></h1>
	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<%= form_for(user, url: url) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :name %>
				<%= f.text_field :name, autofocus: true, class: "form-control" %>

				<%= f.label :email %>
				<%= f.email_field :email, class: "form-control" %>

				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control" %>

				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation, class: "form-control" %>

				<%= f.submit yield(:button_text), class: "btn btn-lg btn-primary" %>
			<% end %>

			<% unless user.email.nil? %>
				<%= gravatar_for user %>
				<%= link_to "Change Photo", "http://gravatar.com/emails", target: :_blank, rel: 'noopener' %>
			<% end %>
		</div>
		<div class="col-md-4">
		</div>		
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
						html: { method: :delete, remote: true } ) do |f| %>
	<%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to gravatar_for(user, size: 60), user %>
	<%= link_to user.name, user %>
	<% if current_user.admin? || current_user?(user) %>
		| <%= link_to "Delete User", user, method: :delete,
																		 data: { confirm: "Delete User Profile?" },
																		 class: "btn btn-danger" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:page_title, "Edit Profile | #{@user.name}") %>
<% provide(:form_title, "Edit Profile of #{@user.name}") %>
<% provide(:button_text, "Update profile") %>

<%= render 'form', user: @user, url: user_path(@user) %>

app/views/users/index.html.erb
<% provide(:page_title, "Users Overview") %>

<h1 class="center">Users Overview</h1>
<div class="content-card">
	<%= will_paginate(@users, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer,
														class: "pagination-bar-top") %>
	<ul class="users">
			<%= render @users %>
	</ul>
	<%= will_paginate(@users, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer,
														class: "pagination-bar-bottom") %>
</div>

app/views/users/new.html.erb
<% provide(:page_title, "Sign up") %>
<% provide(:form_title, "Create new account") %>
<% provide(:button_text, "Create account") %>

<%= render 'form', user: @user, url: signup_path %>

app/views/users/show.html.erb
<% provide(:page_title, "User Profile: #{@user.name}") %>

<div class="content-card">
	<div class="row">
		<div class="col-auto">
			<div class="row show-identity">
				<div class="col-auto">
					<%= gravatar_for(@user, size: 100) %>
				</div>
				<div class="col-auto">
					<h3><%= @user.name %></h3>
					<% if current_user?(@user) %>
						<p>
							<%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %>
						</p>
						<p>
							<%= link_to "Delete Account", user_path(@user),
																						method: :delete,
																						data: { confirm: "Delete Account?" },
																						class: "btn btn-danger" %>
						</p>
					<% end %>		
				</div>
			</div>
			<hr>
			<section class="col-md-12 stats">
				<%= render 'shared/stats' %>
			</section>
			<section class="col-md-12">
				<%= render 'follow_form' if logged_in? %>
			</section>

		</div>
		<div class="col-auto">
			<% if @user.microposts.any? %>
				<ol class="microposts">
					<h2>Microposts (<%= @user.microposts.count %>)</h2>
					<%= render @microposts %>
				</ol>
				<%= will_paginate(@microposts, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer,
																			 class: "pagination-bar-bottom") %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="content-card">
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<div class="row">
					<div class="col-auto">
						<%= link_to gravatar_for(@user, size: 150), user_path(@user) %>
					</div>
					<div class="col-auto">
						<p><%= link_to @user.name, user_path(@user) %></p>
						<p><%= pluralize(@user.microposts.count, "micropost") %></p>
					</div>
				</div>
				<hr>
			</section>
			<section class="stats">
				<%= render 'shared/stats' %>
				<% if @users.any? %>
					<div class="user_avatars">
						<% @users.each do |user| %>
							<%= link_to gravatar_for(user, size: 30), user %>
						<% end %>
					</div>
				<% end %>
			</section>
		</aside>
		<div class="col-md-8">
			<h2 style="font-weight: bold"><%= @title %></h2>
			<% if @users.any? %>
				<ul class="users">
						<%= render @users %>
				</ul>
				<%= will_paginate(@users, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer,
																	class: "pagination-bar-bottom") %>
			<% else %>
				<% if @title == "Following" %>
					<p>Currently not following any users</p>
				<% else %>
					<p>Currently no users following</p>
				<% end %>
			<% end %>
		</div>
	</div>
</div>