config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users, except: [:new, :create] do
    member do
      get :following, :followers
    end
  end
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate(@feed_items, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer,
																 class: "pagination-bar-bottom") %>

<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.text_area :content, autofucus: true, rows: 8, placeholder: "Compose new micropost..." %>

	<%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png", class: "picture" %>

	<%= f.submit "Create micropost", class: "btn btn-primary" %>

<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="row">
	<div class="col-auto center">
		<%= link_to(following_user_path(@user), class: "stat", id: "following") do %>
			<p><%= @user.following.count %></p>
			<p>following</p>
		<% end %>
	</div>
	<div class="col-auto center" id="followers">
		<%= link_to(followers_user_path(@user), class: "stat") do %>
			<p><%= @user.followers.count %></p>
			<p><%= "follower".pluralize(@user.followers.count) %></p>
		<% end %>
	</div>
</div>
<hr>

app/views/shared/_user_info.html.erb
<div class="row">
	<div class="col-auto">
		<%= link_to gravatar_for(current_user, size: 150), user_path(current_user) %>
	</div>
	<div class="col-auto">
		<p><%= link_to current_user.name, user_path(current_user) %></p>
		<p><%= pluralize(current_user.microposts.count, "micropost") %></p>
	</div>
</div>