config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users, except: [:new, :create] do
    member do
      get :following, :followers
    end
  end
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_default_header.html.erb
<%= csrf_meta_tags %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<%= link_to "The Ruby on Rails Tutorial", "http://railstutorial.org" %>
		by
		<%= link_to "Michael Hartl", "http://michaelhartl.com" %>
	</small>
	<nav>
		<ul>
			<li>
      	<%= link_to "About", about_path %>
			</li>
			<li>
      	<%= link_to "Contact", contact_path %>
			</li>
			<li>
      	<%= link_to "News", "http://news.railstutorial.org" %>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="header-card">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  		<%= link_to "SAMPLE APP", root_path, id: "navbar-brand", class: "col-lg-3" %>
	  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    		<span class="navbar-toggler-icon"></span>
	  		</button>
		  <div class="collapse navbar-collapse col-lg-9" id="navbarNav">
		    <ul class="navbar-nav container justify-content-end">
		      <li class="nav-item <%= active("static_pages", "home") %>">
		      	<%= link_to "Home", root_path, class: "nav-link" %>
		      </li>
		      <li class="nav-item <%= active("static_pages", "help") %>">
		      	<%= link_to "Help", help_path, class: "nav-link" %>
		      </li>
	      	<% if logged_in? %>
			      <li class="nav-item">
			     		<%= link_to "Users", users_path, class: "nav-link" %>
			      </li>
			      <li class="nav-item dropdown">
			      	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
			      		 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          			Account
        			</a>
			      	<ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
					      <li>
					     		<%= link_to "#{current_user.name}", current_user, class: "nav-link dropdown-item" %>
					      </li>
					      <li>
					     		<%= link_to "Settings", edit_user_path(current_user), class: "nav-link dropdown-item" %>
					      </li>
					      <li class="dropdown-divider"></li>
					      <li>
					     		<%= link_to "Logout", logout_path, method: :delete,
																				     				 class: "nav-link dropdown-item" %>
					      </li>
					    </ul>
					  </li>
			    <% else %>
			      <li class="nav-item <%= active("sessions", "new") %>">
			     		<%= link_to "Login", login_path, class: "nav-link" %>
			      </li>
	      	<% end %>
			    </ul>
		  </div>
	</nav>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <%= render 'layouts/default_header' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
 		<%= render 'layouts/header' %>
 		<div class="content-container">
      <% flash.each do |msg_type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
      <% end %>
      <%= yield %>
    </div>
 		<%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  </body>
</html>